### ISSUE TITLE
я вообще не понимаю, откуда Вы собираетесь второй вектор брать, как он в метод попадет?

### ISSUE THREAD

**Issue by TkatchGA** [TkatchGA/Tkachenko-Georgy-ISM-114#10]
я вообще не понимаю, откуда Вы собираетесь второй вектор брать, как он в метод попадет?

_Originally posted by @MarinaPaley in https://github.com/TkatchGA/Tkachenko-Georgy-ISM-114/pull/9#discussion_r602568347_

**Comment by MarinaPaley** [comment]
Не очень понимаю, для чего Вы создали данный issue.
