### ISSUE TITLE
Начало работы с ЯВУ

### ISSUE THREAD

**Issue by TkatchGA** [TkatchGA/Tkachenko-Georgy-ISM-114#3]
1. Установил программу Sourcetree для визуализации локального репозитория. Выбрал её, так как моя система MacOS.
2. Создал несколько ветвей и коммитил изменения в них. 
3. На данный момент хочу объединить созданные ветви.

**Comment by Const-Phi** [comment]
1. Sourcetree [не единственная](https://git-scm.com/download/gui/mac) программа для визуализации под MacOS, но, вероятно, одна из проработанных.
2. Похвально.
3. Стоит посмотреть в сторону [merge vs rebase](https://www.atlassian.com/ru/git/tutorials/merging-vs-rebasing).

### Сверх того, но про _начало работы_
Я бы обратил внимание на тот факт, что в `master` лежит `*.cpp`, но нет [`.gitignore`](https://www.atlassian.com/git/tutorials/saving-changes/gitignore), а имело бы смысл сделать наоборот.
![image](https://user-images.githubusercontent.com/8349213/111920401-c5544700-8a9f-11eb-81ad-7cecee7c93e6.png)
Про то как и где его сгенерировать (как и о многом другом) можно прочитать в &laquo;методичке&raquo; в картинках, которая должна лежать в учебных материалах вашей группы (в MS Teams). Если коротко, то есть специальные ресурсы, позволяющие генерировать как  `.gitignore` ([генератор](https://www.toptal.com/developers/gitignore) и [документация](https://docs.gitignore.io/)), так и [`.gitattributes`](https://git-scm.com/book/ru/v2/Настройка-Git-Атрибуты-Git) ([генератор](https://gitattributes.io/)).
